### ISSUE TITLE
How to run this automation

### ISSUE THREAD

**Issue by fabrizio-mendez-Imprivata** [Xray-App/xray-automation-js#11]
Hello Sergio, 

I have a work project in which  I need to import test results to Xray automatically (with code), found your repo online and followed the instructions on the readme you added. However I'm still struggling to know how to run this project? Is there a way that we can connect via email or social networks to help me out? I would appreciate it greatly!

**Comment by bitcoder** [comment]
Hi @fabrizio-mendez-Imprivata ,
this is a client library to interact with Xray API, namely to upload test automation results from  test automation frameworks.
It's not a test automation library in itself.
I think the examples on the README are clear enough but I'm open to improvements/further clarification ofc.
Which concrete questions do you have?
