### ISSUE TITLE
d.ts missing?

### ISSUE THREAD

**Issue by BenoitDuffez** [Xray-App/xray-automation-js#9]
Trying to use it with TypeScript yields:

```
TS7016: Could not find a declaration file for module '@xray-app/xray-automation'. 
'/xxx/node_modules/@xray-app/xray-automation/dist/cjs/index.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/xray-app__xray-automation` if it exists or add a new declaration (.d.ts) file containing `declare module '@xray-app/xray-automation';`
```

Am I missing something?

**Comment by bitcoder** [comment]
Hmm I need to check; help is appreciated

**Comment by bitcoder** [comment]
How can I replicate this @BenoitDuffez ?
And which version of this package were you using?

**Comment by bitcoder** [comment]
The types should be bundled together with the code, as part of the package '@xray-app/xray-automation'. This as of v0.3.0.
We're not publishing a separate package just for the types.

For internal ref: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by bitcoder** [comment]
@BenoitDuffez  can you please with the latest version of this package?

**Comment by KKonstantinov** [comment]
@bitcoder  Hello, having the same issue.

You are specifying types, but then the types folder is missing in the dist/ folder.

<img width="704" alt="image" src="https://github.com/Xray-App/xray-automation-js/assets/655541/de580dff-0412-4eb3-ac70-a27ba762b06b">

<img width="807" alt="image" src="https://github.com/Xray-App/xray-automation-js/assets/655541/085d5f2c-e0ab-4486-a7ad-d9f08d1d5e0a">

**Comment by bitcoder** [comment]
@BenoitDuffez @KKonstantinov  I've create a branch "include_types" with a potential fix. can you please try it out and let me know?

**Comment by KKonstantinov** [comment]
This should be fine - could you publish it to npm so we can test it when installed?
